# -*- coding: utf-8 -*-
"""ML-L1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16I7OiOWQ5GUAbk-0dl7myCYwn7txrW4U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv("titanic.csv")

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.isnull().sum()

# Correlation between variable
corr = df.select_dtypes(include=np.number).corr()
corr.Survived.sort_values(ascending=False).head(10)

df["Embarked"].unique()

plt.figure(figsize=(8,5))
sns.heatmap(df.isnull(), cbar=False, cmap="coolwarm")
plt.title("Missing Values")
plt.show()

df["Embarked"] = df["Embarked"].replace("S" , 0)
df["Embarked"] = df["Embarked"].replace("C" , 1)
df["Embarked"] = df["Embarked"].replace("Q" , 2)

df["Age"].fillna(df["Age"].median(), inplace=True)

df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

df.isnull().sum()

df.drop("Cabin" , axis=1, inplace=True)

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

sns.boxplot(x=df["Age"])
plt.show()

sns.boxplot(x=df["Fare"])
plt.show()

Q1=df["Fare"].quantile(0.25)
Q3=df["Fare"].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
df=df[(df["Fare"] >= lower) & (df["Fare"] <= upper)]

sns.boxplot(x=df["Fare"])
plt.show()

Q1=df["Age"].quantile(0.25)
Q3=df["Age"].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
df=df[(df["Age"] >= lower) & (df["Age"] <= upper)]

sns.boxplot(x=df["Age"])
plt.show()

df["Sex"] = df["Sex"].replace("male", 0)
df["Sex"] = df["Sex"].replace("female", 1)

plt.figure(figsize = (14,8))
df['Sex'].value_counts().plot(kind = "pie" , autopct = "%.2f")
plt.show()

df["Embarked"].unique()

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

df.head()

#univariate analysis
plt.figure(figsize=(6,4))
sns.histplot(df["Age"],bins=20,kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df["Fare"],bins=20,kde=True)
plt.title("Fare Distribution")
plt.show()

sns.countplot(x="Sex", data=df)
plt.title("Gender Count")
plt.show()

sns.countplot(x="Pclass", data=df)
plt.title("Pclass Count")
plt.show()

sns.countplot(x="Embarked", data=df)
plt.title("Embarked Count")
plt.show()

#Bivariate analysis
sns.countplot(x="Sex", hue="Survived", data=df)
plt.title("Gender vs Survived")
plt.show()

#Bivariate analysis
sns.countplot(x="Embarked", hue="Survived", data=df)
plt.title("Embarked vs Survived")
plt.show()

#Bivariate analysis
sns.countplot(x="Pclass", hue="Survived", data=df)
plt.title("Pclass vs Survived")
plt.show()

sns.scatterplot(x="Age", y="Fare", data=df)
plt.show()

plt.figure(figsize=(10,8))
numeric_df = df.select_dtypes(include=["number"])
sns.heatmap(numeric_df.corr(),
annot=True,
cmap = "coolwarm")
plt.show()

#Feature Scaling
X=df.drop("Survived",axis=1)
Y=df["Survived"]

X=X.drop(["PassengerId","Name","Ticket"],axis=1)

#Standard scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X[["Age","Fare"]]=scaler.fit_transform(X[["Age","Fare"]])

X.head(15)

#Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=42)

print("Training data:",X_train.shape)
print("Training data:",X_test.shape)

print(X_train.head())