# -*- coding: utf-8 -*-
"""ML-l2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YX6b4VgaMZ4y6QKrz_6rchArPWHzUIhr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

df = pd.read_csv("USA_Housing.csv")

df.head()

df.isnull().sum()

df.duplicated().sum()

#to drop the address feature
df.drop("Address" , axis=1, inplace=True)

df.info()

df.describe()

sns.boxplot(x=df["Price"])
plt.show()

sns.boxplot(x=df["Avg. Area Income"])
plt.show()

sns.boxplot(x=df["Area Population"])
plt.show()

Q1 = df["Price"].quantile(0.25)
Q3 = df["Price"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df["Price"] >= lower) & (df["Price"] <= upper)]

sns.histplot(df["Price"], kde=True)
plt.show()

sns.histplot(df["Avg. Area Income"], kde=True)
plt.show()

sns.scatterplot(x="Avg. Area Income", y="Price", data=df)
plt.show()

sns.scatterplot(x="Area Population", y="Price", data=df)
plt.show()

plt.figure(figsize=(10,8))
numeric_df = df.select_dtypes(include=["number"])
sns.heatmap(numeric_df.corr(),
annot=True,
cmap = "Greens")
plt.show()

print(df.shape)

X = df.drop(["Price"], axis=1)
y = df["Price"]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

print("Training Data:", x_train.shape)
print("Testing Data:", x_test.shape)

"""Simple Linear Regression"""

x=df[['Avg. Area Income']]
y=df['Price']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

from sklearn.linear_model import LinearRegression
slr_model=LinearRegression()
slr_model.fit(x_train, y_train)

y_pred=slr_model.predict(x_test)

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

print("Simple Linear Regression")
print("------------------------")
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

print("Intercept:",slr_model.intercept_)
print("Slope:",slr_model.coef_[0])

plt.figure(figsize=(8, 6))
plt.scatter(x_test,y_test,color='blue',label='Actual Data')
plt.plot(x_test,y_pred,color='red',linewidth=2,label='Regression Line')
plt.xlabel('Average Area Income')
plt.ylabel('Price')
plt.title('Simple Linear Regression')
plt.legend()
plt.show()

income= float(input("Enter Average Area Income:"))
new_data=np.array([[income]])
prediction=slr_model.predict(new_data)
print("Predicted Price=${:.2f}".format(prediction[0]))

from sklearn.model_selection import GridSearchCV

"""Ridge Regression"""

from sklearn.linear_model import Ridge
ridge = Ridge()

ridge.fit(x_train, y_train)

ridge_pred = ridge.predict(x_test)

print("Default Ridge Regression:", r2_score(y_test, ridge_pred))

param_grid ={'alpha':[0.001,0.01,0.1,1,10,100]}
grid_ridge = GridSearchCV(estimator=Ridge(),param_grid=param_grid,scoring='r2',cv=5)
grid_ridge.fit(x_train,y_train)

print("Best Alpha:",grid_ridge.best_params_)
print(grid_ridge.best_score_)
best_ridge = grid_ridge.best_estimator_
ridge_pred = best_ridge.predict(x_test)

print("MAE :",mean_absolute_error(y_test,ridge_pred))
print("MSE :",mean_squared_error(y_test,ridge_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))