# -*- coding: utf-8 -*-
"""ML-L4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1436IM8exnzsQcLj-SeuQG6ULqcjMwZpR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("WineQT.csv")

df.head()

df.tail()

df.shape

df.isnull().sum()

# Univariate Analysis
plt.figure(figsize=(6,4))
sns.histplot(df["alcohol"], bins=20, kde=True)
plt.title("Alcohol Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x=df["quality"])
plt.title("Wine Quality Distribution")
plt.show()

numeric_cols = df.select_dtypes(include='number').columns
for col in numeric_cols:
    plt.figure(figsize=(7,4))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

# Remove target column
features = df.drop(columns=['quality'])
Q1 = features.quantile(0.25)
Q3 = features.quantile(0.75)
# Calculate IQR
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers_mask = features[(features < lower_bound) | (features > upper_bound)]
outlier_count = outliers_mask.sum()
outlier_percentage = (outlier_count / len(features)) * 100
outlier_summary = pd.DataFrame({
    'Q1': Q1,
    'Q3': Q3,
    'IQR': IQR,
    'Lower Bound': lower_bound,
    'Upper Bound': upper_bound,
    'Outlier Count': outlier_count,
    'Outlier Percentage': outlier_percentage
})

outlier_summary.round(3)

plt.figure(figsize=(10,6))
sns.countplot(x='quality',data=df)
plt.title('Distribution of Wine Quality')
plt.show()

# Bivariate analysis
sns.boxplot(x='quality',y='alcohol',data=df)
plt.title('Alcohol vs Wine quality')
plt.show()

features = ['fixed acidity', 'volatile acidity', 'citric acid']
for col in features:
    plt.figure(figsize=(7,4))
    sns.boxplot(x='quality', y=col, data=df)
    plt.title(f'{col} vs Wine Quality')
    plt.show()

sns.scatterplot(x='alcohol',y='quality',data=df)
plt.title('Alcohol vs Wine quality')
plt.show()

sns.scatterplot(x='volatile acidity',y='quality',data=df)
plt.title('Volatile acidity vs Wine quality')
plt.show()

# Multivariate Analysis
plt.figure(figsize=(10,6))
corr = df.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

selected = ['alcohol', 'volatile acidity', 'sulphates', 'citric acid', 'quality']
sns.pairplot(df[selected], hue='quality')
plt.show()

#multivariate analysis using quality groups
df['quality_group'] = pd.cut(
    df['quality'],
    bins=[0,5,6,10],
    labels=['Low','Medium','High']
    )

sns.boxplot(
    x='quality_group',
    y='alcohol',
    data=df
    )
plt.title('Alcohol Distribution Across Quality Groups')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                                f1_score, classification_report , confusion_matrix, ConfusionMatrixDisplay)

X = df.drop('quality', axis=1)
y = df['quality']

print(y.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20,
    random_state=42,
    stratify=y
)

criterion='entropy'

dt_model = DecisionTreeClassifier(
    criterion='entropy',
    random_state=42
)

# Convert target labels to numbers
y = df['quality_group'].map({
    'Low': 0,
    'Medium': 1,
    'High': 2
})
X = df.drop(['quality', 'quality_group'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

y_train_pred = dt_model.predict(X_train)
y_test_pred = dt_model.predict(X_test)

train_accuracy = accuracy_score(y_train, y_train_pred)
print("Training Accuracy:", train_accuracy)

test_accuracy = accuracy_score(y_test, y_test_pred)
print("Testing Accuracy:", test_accuracy)

print("Precision:",
      precision_score(y_test, y_test_pred, average='weighted'))
print("Recall:",
      recall_score(y_test, y_test_pred, average='weighted'))
print("F1 Score:",
      f1_score(y_test, y_test_pred, average='weighted'))
print(classification_report(y_test, y_test_pred))

cm = confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(6, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted Quality')
plt.ylabel('Actual Quality')
plt.title('Confusion Matrix - Decision Tree')

plt.show()

print("tree depth:", dt_model.get_depth())
print("number of leaves:", dt_model.get_n_leaves())

plt.figure(figsize=(25,15))

plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=[str(c) for c in sorted(y.unique())],
    filled=True,
    rounded=True,
    fontsize=8
)

plt.title("decision tree-entropy")
plt.show()

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(24,12))

plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=[str(c) for c in sorted(y.unique())],
    filled=True,
    rounded=True,
    impurity=True,
    precision=2,
    fontsize=10,
    max_depth=10
)

plt.title("decision tree top 3 levels", fontsize=18)
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc, roc_auc_score
import matplotlib.pyplot as plt
import numpy as np

classes = sorted(y_test.unique())

y_test_bin = label_binarize(y_test, classes=classes)
y_score = dt_model.predict_proba(X_test)

plt.figure(figsize=(10, 7))

for i, class_label in enumerate(classes):
    fpr, tpr, thresholds = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(
        fpr,
        tpr,
        linewidth=2,
        label=f'Quality {class_label} (AUC= {roc_auc:.2f})'
    )

plt.plot([0, 1], [0, 1], linestyle='--', label='Random Classifier')

plt.xlabel('false positive rate')
plt.ylabel('true positive rate')
plt.title('Receiver Operating Characteristic (ROC) Curve: before hyperparameter tuning')
plt.legend()
plt.grid()
plt.show()

overall_auc_before = roc_auc_score(
    y_test_bin,
    y_score,
    multi_class='ovr',
    average='weighted'
)

print('overall auc-roc before tuning', round(overall_auc_before, 4))

# Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

param_grid = {
    'criterion': ['entropy'],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 4, 8],
    'max_features': [None, 'sqrt', 'log2'],
    'ccp_alpha': [0.001, 0.01, 0.05]
}

grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print('best parameters')
print(grid.best_params_)

print('best cross validation accuracy')
print(grid.best_score_)

best_tree = grid.best_estimator_

# Prediction and Evaluation
y_pred = best_tree.predict(X_test)

print(classification_report(y_test, y_pred))
print("accuracy =", accuracy_score(y_test, y_pred))

from sklearn.model_selection import cross_val_score
scores = cross_val_score(
    best_tree,
    X,
    y,
    cv=10,
    scoring='accuracy'
)
print(scores)
print("average accuracy=", scores.mean())
print("std=", scores.std())

from sklearn.model_selection import learning_curve
train_sizes, train_scores, test_scores = learning_curve(
    best_tree,
    X, y,cv=5,
    scoring='accuracy'
)

plt.figure(figsize=(8,5))
plt.plot(
    train_sizes,
    train_scores.mean(axis=1),
    marker='o',
    label='training accuracy'
)
plt.plot(
    train_sizes,
    test_scores.mean(axis=1),
    marker='o',
    label='validation accuracy'
)
plt.xlabel("train size")
plt.ylabel("accuracy")
plt.title("learning curve")

plt.legend()
plt.show()

new_wine = pd.DataFrame([{
    'Id': 1,
    'fixed acidity': 7.4,
    'volatile acidity': 0.7,
    'citric acid': 0.20,
    'residual sugar': 2.0,
    'chlorides': 0.065,
    'free sulfur dioxide': 15.0,
    'total sulfur dioxide': 40.0,
    'density': 1.29,
    'pH': 3.4,
    'sulphates': 0.54,
    'alcohol': 9.4
}])
new_wine = new_wine[best_tree.feature_names_in_]
prediction = best_tree.predict(new_wine)
print("Predicted wine quality:", prediction[0])